name: GamemodeUI
main: GamemodeUI\LaithYT\Main
version: 1.0.1
api: [3.0.0]
author: LaithYT
description: Easily Change Gamemode
website: https://github.com/laith98

commands: 
 gm:
    description: "GamemodeUI Command"

permissions:
 gamemodeui.command:
    description: "GamemodeUI Permission"
    defualt: op
 gamemodeui.form:
    description: "GamemodeUI Permission to Open Form"
    defualt: op
