name: GamemodeUI
main: GamemodeUI\LaithYT\Main
version: 1.0.1
api: [3.0.0]
author: LaithYT
description: Easily Chang Gamemode
website: https://github.com/laith98

commands: 
 gm:
    description: "GamemodeUI Command"
    permission: "gm.command"
permissions:
 gm.command:
    description: "GamemodeUI Permission"
    defualt: op
 gm.form:
    description: "GamemodeUI Permission Open Form"
    defualt: op
